import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  computeBodyHash,
  decisionBaseId,
  loadDecisions,
  takenDecisionIds,
  writeDecision,
  type DecisionRecord,
  type DecisionStatus,
} from "../store/decisions.js";

/** `reposkein-mcp adr export|import` — the human/interop surface.
 *
 *  Export renders the committed decision records to docs/adr/NNNN-slug.md in
 *  Nygard section format for PR review and adr-tools/log4brains/Backstage
 *  interop. It is a DERIVED view: the JSON records stay the system of record —
 *  a second authored store would recreate decision drift.
 *
 *  Import is the path in for teams arriving with an existing markdown ADR
 *  log: Nygard/MADR-style documents become records (decided_by "human", no
 *  anchors — those come later via record/reaffirm flows). */

const STATUSES: readonly DecisionStatus[] = [
  "proposed",
  "accepted",
  "rejected",
  "deprecated",
  "superseded",
];

const GENERATED_MARKER = "<!-- reposkein:";

/** Escapes line-leading '#' in prose so recorded text can never masquerade as
 *  a section heading — the write guard allows newlines, and an injected
 *  "## Status" would otherwise flip fields on re-import. parseAdrMarkdown
 *  unescapes symmetrically. */
function escapeProse(text: string): string {
  return text
    .split("\n")
    .map((l) => (l.startsWith("#") ? `\\${l}` : l))
    .join("\n");
}

/** Nygard-style markdown for one record. `n` is the export ordinal. */
export function renderAdrMarkdown(rec: DecisionRecord, n: number): string {
  const lines: string[] = [];
  lines.push(`# ${n}. ${rec.title}`, "");
  lines.push(`Date: ${rec.decided_at}`, "");
  lines.push("## Status", "");
  lines.push(rec.status + (rec.superseded_by ? ` (superseded by ${rec.superseded_by})` : ""), "");
  lines.push("## Context", "", escapeProse(rec.context), "");
  lines.push("## Decision", "", escapeProse(rec.decision), "");
  if (rec.consequences) lines.push("## Consequences", "", escapeProse(rec.consequences), "");
  if (rec.alternatives) lines.push("## Alternatives", "", escapeProse(rec.alternatives), "");
  const governs = [
    ...rec.anchors.map((a) => `- ${a.path || a.node_id} (${a.kind || "node"})`),
    ...rec.paths.map((p) => `- ${p}`),
  ];
  if (governs.length > 0) lines.push("## Governs", "", ...governs, "");
  if (rec.supersedes.length > 0) {
    lines.push("## Supersedes", "", ...rec.supersedes.map((s) => `- ${s}`), "");
  }
  lines.push(`<!-- reposkein:${rec.id} — generated by \`reposkein-mcp adr export\`; edit via record_decision, not here -->`);
  return lines.join("\n") + "\n";
}

/** Renders every decision to outDir, numbered by sorted id (deterministic:
 *  same log → same files, byte for byte). Previously GENERATED files (marker
 *  comment) are removed first so an ordinal shift never leaves stale
 *  duplicates; hand-written documents in the same dir are untouched.
 *  Returns the file count. */
export function exportAdrMarkdown(repoPath: string, outDir: string): number {
  const { decisions } = loadDecisions(repoPath);
  mkdirSync(outDir, { recursive: true });
  for (const f of readdirSync(outDir)) {
    if (!f.endsWith(".md")) continue;
    try {
      if (readFileSync(join(outDir, f), "utf8").includes(GENERATED_MARKER)) {
        rmSync(join(outDir, f));
      }
    } catch {
      // unreadable → leave it alone
    }
  }
  let n = 0;
  for (const rec of decisions) {
    n++;
    const file = `${String(n).padStart(4, "0")}-${rec.id.replace(/^adr:/, "")}.md`;
    writeFileSync(join(outDir, file), renderAdrMarkdown(rec, n));
  }
  return n;
}

export interface ParsedAdrDoc {
  title: string;
  status: DecisionStatus;
  date?: string;
  context?: string;
  decision?: string;
  consequences?: string;
  alternatives?: string;
}

/** Parses a Nygard/MADR-style ADR document. Returns null when the document
 *  has no recognizable title/status/decision (not an ADR). */
export function parseAdrMarkdown(text: string): ParsedAdrDoc | null {
  const lines = text.split("\n");
  let title: string | null = null;
  let date: string | undefined;
  const sections = new Map<string, string[]>();
  let current: string[] | null = null;
  for (const raw of lines) {
    const line = raw.trimEnd();
    const h1 = /^#\s+(.+)$/.exec(line);
    if (h1 && title === null) {
      // Strip an adr-tools "N. " ordinal prefix.
      title = h1[1]!.replace(/^\d+\.\s+/, "").trim();
      continue;
    }
    const h2 = /^##\s+(.+)$/.exec(line);
    if (h2) {
      const name = h2[1]!.trim().toLowerCase();
      // First heading wins: a duplicate later section (e.g. injected into
      // prose) must not replace the real one.
      if (sections.has(name)) {
        current = null;
      } else {
        current = [];
        sections.set(name, current);
      }
      continue;
    }
    const dateLine = /^Date:\s*(\d{4}-\d{2}-\d{2})\s*$/.exec(line);
    if (dateLine && current === null) {
      date = dateLine[1]!;
      continue;
    }
    if (current !== null && line.trim() !== "" && !line.startsWith("<!--")) {
      // Unescape the export-side heading escape.
      current.push(line.trim().replace(/^\\#/, "#"));
    }
  }
  const section = (name: string): string | undefined => {
    const body = sections.get(name);
    if (!body || body.length === 0) return undefined;
    return body.join(" ");
  };
  const statusRaw = section("status");
  const statusWord = statusRaw?.split(/[\s(]/, 1)[0]?.toLowerCase();
  const status = STATUSES.find((s) => s === statusWord);
  const decision = section("decision");
  if (!title || !status || !decision) return null;
  const out: ParsedAdrDoc = { title, status };
  if (date !== undefined) out.date = date;
  const context = section("context");
  if (context !== undefined) out.context = context;
  out.decision = decision;
  const consequences = section("consequences");
  if (consequences !== undefined) out.consequences = consequences;
  const alternatives = section("alternatives");
  if (alternatives !== undefined) out.alternatives = alternatives;
  return out;
}

export interface ImportResult {
  imported: number;
  skipped: string[];
  /** Documents whose (date, title) id already exists — left untouched, which
   *  is what makes re-import idempotent. */
  existing: number;
}

/** Imports every .md in srcDir as a decision record. A document whose
 *  (date, title) base id already exists is counted as `existing` and left
 *  untouched — re-import is idempotent, never duplicating; unparseable
 *  documents are skipped and reported, never fatal. */
export function importAdrMarkdown(
  repoPath: string,
  srcDir: string,
  opts: { fallbackDate: string }
): ImportResult {
  let files: string[];
  try {
    files = readdirSync(srcDir).filter((f) => f.endsWith(".md"));
  } catch {
    return { imported: 0, skipped: [], existing: 0 };
  }
  const taken = takenDecisionIds(repoPath);
  let imported = 0;
  let existing = 0;
  const skipped: string[] = [];
  for (const f of files.sort()) {
    let doc: ParsedAdrDoc | null = null;
    try {
      doc = parseAdrMarkdown(readFileSync(join(srcDir, f), "utf8"));
    } catch {
      doc = null;
    }
    if (!doc) {
      skipped.push(f);
      continue;
    }
    const date = doc.date ?? opts.fallbackDate;
    const id = decisionBaseId(date, doc.title);
    if (taken.has(id)) {
      existing++;
      continue;
    }
    taken.add(id);
    const rec: DecisionRecord = {
      id,
      title: doc.title,
      status: doc.status,
      context: doc.context ?? "",
      decision: doc.decision ?? "",
      anchors: [],
      paths: [],
      supersedes: [],
      decided_at: date,
      decided_by: "human",
      trigger: { kind: "manual" },
      body_hash: "",
    };
    if (doc.consequences !== undefined) rec.consequences = doc.consequences;
    if (doc.alternatives !== undefined) rec.alternatives = doc.alternatives;
    rec.body_hash = computeBodyHash(rec);
    writeDecision(repoPath, rec);
    imported++;
  }
  return { imported, skipped, existing };
}

/** Entry point for `reposkein-mcp adr <export|import> [path] [dir]`. */
export function runAdr(sub: string | undefined, repoPath: string, dir?: string): number {
  if (sub === "export") {
    const out = dir ?? join(repoPath, "docs", "adr");
    const n = exportAdrMarkdown(repoPath, out);
    console.error(`exported ${n} decision${n === 1 ? "" : "s"} to ${out}`);
    return 0;
  }
  if (sub === "import") {
    const src = dir ?? join(repoPath, "docs", "adr");
    const today = new Date().toISOString().slice(0, 10);
    const r = importAdrMarkdown(repoPath, src, { fallbackDate: today });
    console.error(
      `imported ${r.imported} decision${r.imported === 1 ? "" : "s"} from ${src}` +
        (r.existing ? `; ${r.existing} already present` : "") +
        (r.skipped.length ? `; skipped: ${r.skipped.join(", ")}` : "")
    );
    return 0;
  }
  console.error("usage: reposkein-mcp adr <export|import> [repoPath] [dir]");
  return 1;
}
