import { mkdirSync, copyFileSync, existsSync, readFileSync, appendFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { ensureIndexerBinary, packageRoot, platformKey, cargoInstallFallbackMessage } from "../indexer/fetchBinary.js";
import { spawnIndexer } from "../indexer/runIndexer.js";
import { writeAgentConfigs, formatAdapterResult, type AgentId, type WriteAgentConfigsOptions } from "./agentAdapters.js";
import { runChecks, renderDoctorReport } from "./doctor.js";

/** Where the navigation skill is installed for a repo (Claude project skills). */
export function skillTargetPath(repoPath: string): string {
  return join(repoPath, ".claude", "skills", "reposkein-graph-rag", "SKILL.md");
}

/** The bundled SKILL.md inside the installed package (dist/SKILL.md). */
export function bundledSkillPath(): string {
  return join(packageRoot(), "dist", "SKILL.md");
}

/** MCP server config snippet the user adds to their client (e.g. .mcp.json). */
export function mcpConfigSnippet(repoPath: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        reposkein: {
          command: "reposkein-mcp",
          env: { REPOSKEIN_REPO_PATH: repoPath },
        },
      },
    },
    null,
    2
  );
}

/** Per-machine MCP config files setup writes to a repo root: they hold absolute
 *  paths and a local backend password, so they must never be committed.
 *  Written as gitignore patterns (always forward-slash, regardless of OS). */
const LOCAL_MCP_CONFIG_FILES = [".mcp.json", "opencode.json", ".cursor/mcp.json"] as const;

/** Idempotently add the per-machine MCP config files to the repo's .gitignore
 *  (creating it if absent), so `reposkein-mcp init` never leaves them tracked. */
export function ensureLocalConfigGitignored(repoPath: string): void {
  const gitignorePath = join(repoPath, ".gitignore");
  const current = existsSync(gitignorePath) ? readFileSync(gitignorePath, "utf8") : "";
  const present = new Set(current.split(/\r?\n/).map((line) => line.trim()));
  const missing = LOCAL_MCP_CONFIG_FILES.filter((file) => !present.has(file));
  if (missing.length === 0) return;
  const leadingNewline = current.length > 0 && !current.endsWith("\n") ? "\n" : "";
  const block =
    `${leadingNewline}\n# RepoSkein per-machine MCP config (absolute paths + a local backend\n` +
    "# password); regenerated per machine by `reposkein-mcp init`. The derived\n" +
    "# graph is ignored separately by .reposkein/.gitignore.\n" +
    `${missing.join("\n")}\n`;
  appendFileSync(gitignorePath, block);
  console.error(`reposkein: gitignored ${missing.join(", ")} (per-machine config, never commit)`);
}

/** True when `.reposkein/meta.json` is tracked by git — this clone joined a
 *  repo that already has RepoSkein set up (someone else ran `init` and
 *  committed it), rather than being the first machine to set it up (whose
 *  meta.json exists on disk but isn't committed yet). Join mode skips
 *  first-time scaffolding entirely and instead wires up the local agent(s)
 *  automatically (REP-16 T5) — see `runInit`.
 *
 *  Falls back to plain existence when git itself is unavailable (no `git`
 *  binary, or `repoPath` isn't a git repo yet) so `init` still behaves
 *  sensibly outside a git repo rather than throwing. */
export function detectJoinMode(repoPath: string): boolean {
  if (!existsSync(join(repoPath, ".reposkein", "meta.json"))) return false;
  try {
    execFileSync("git", ["ls-files", "--error-unmatch", ".reposkein/meta.json"], {
      cwd: repoPath,
      stdio: ["ignore", "ignore", "ignore"],
    });
    return true;
  } catch {
    return false;
  }
}

/** Where `init --ci` writes the Pages-publish workflow in the target repo. */
export function ciWorkflowTargetPath(repoPath: string): string {
  return join(repoPath, ".github", "workflows", "reposkein-pages.yml");
}

/** Template written by `reposkein-mcp init --ci`: a thin caller of RepoSkein's
 *  reusable publish workflow (see docs/HOSTING.md). Consumers get released
 *  indexer binaries (no Rust toolchain) + a self-contained static export
 *  published to GitHub Pages. Repo owners must still flip Settings → Pages →
 *  "Build and deployment: GitHub Actions" once. */
export function ciWorkflowTemplate(): string {
  return `name: Publish RepoSkein constellation (GitHub Pages)

# Generated by \`reposkein-mcp init --ci\`. See docs/HOSTING.md — "Host your
# constellation" — before enabling: GitHub Pages is PUBLIC by default unless
# you're on GitHub Enterprise with private Pages enabled.
#
# ONE-TIME SETUP (repo owner): Settings → Pages → Build and deployment →
# Source: "GitHub Actions".

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    uses: reposkein/reposkein/.github/workflows/publish-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      repo-path: "."
`;
}

/** `reposkein-mcp init --ci`: writes the Pages-publish workflow template into
 *  the target repo's `.github/workflows/`. Non-destructive: skips (with a
 *  message) if the file already exists, so a re-run never clobbers a repo
 *  owner's edits. Returns whether it wrote the file. */
export function writeCiWorkflow(repoPath: string): { written: boolean; path: string } {
  const path = ciWorkflowTargetPath(repoPath);
  if (existsSync(path)) {
    console.error(`reposkein: ${path} already exists — leaving it untouched.`);
    return { written: false, path };
  }
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, ciWorkflowTemplate(), "utf8");
  console.error(`reposkein: wrote ${path} (see docs/HOSTING.md before enabling GitHub Pages).`);
  return { written: true, path };
}

/** `reposkein-mcp index [path]`: (re)build the code graph at `repoPath` using the
 *  native indexer. The package-friendly way to index — the `reposkein-indexer`
 *  binary is fetched into the package (not on PATH), so end users run this. */
export async function runIndex(repoPath = "."): Promise<number> {
  const bin = await ensureIndexerBinary();
  const r = await spawnIndexer(bin, ["index", repoPath]);
  if (r.stdout.trim()) console.error(r.stdout.trim());
  if (r.code !== 0) {
    console.error(`reposkein: index failed: ${r.stderr || r.stdout}`);
  }
  return r.code;
}

export interface RunInitOptions {
  index?: boolean;
  ci?: boolean;
  /** Explicit `--agents` override for join mode; detected when omitted. */
  agents?: AgentId[];
  /** `--dry-run`: plan agent config writes without touching disk. */
  dryRun?: boolean;
  /** Force join-mode on/off; auto-detected (committed .reposkein/meta.json)
   *  when omitted — see `detectJoinMode`. */
  join?: boolean;
  /** Test-only injection point for the agent-adapter step (fake `exec`/`now`). */
  agentWriteOpts?: Pick<WriteAgentConfigsOptions, "exec" | "now">;
}

/** `reposkein-mcp init [path] [--no-index] [--ci] [--agents <list>] [--dry-run]`:
 *  ensure the indexer, install git hooks, build the initial graph, install
 *  the navigation skill, then either (join mode) auto-write the local
 *  agent(s) MCP config, or (first-time) print the config snippet to paste in
 *  by hand. Pass `index: false` to skip the initial index; `ci: true` to
 *  also write the GitHub Pages publish workflow (see docs/HOSTING.md).
 *
 *  Join mode (REP-16 T5): auto-detected when `.reposkein/meta.json` is
 *  already committed (`detectJoinMode`) — i.e. someone cloned a repo that
 *  already has RepoSkein set up. Skips nothing structural (hooks/index/skill
 *  still run so a stale local checkout gets caught up) but additionally
 *  writes `.mcp.json` / `opencode.json` / `.cursor/mcp.json` for whichever
 *  agent(s) are detected present (or `opts.agents`), then prints a doctor
 *  summary instead of a config snippet to copy by hand.
 *
 *  Unsupported platform (darwin-x64, win32-arm64, no REPOSKEIN_INDEXER_BIN):
 *  prints cargo-install fallback instructions and CONTINUES instead of
 *  crashing — hooks + the initial index are skipped (nothing to run them
 *  with), but the skill, CI workflow, and (in join mode) agent config are
 *  still written, and the function returns 0. */
export async function runInit(repoPath = ".", opts: RunInitOptions = {}): Promise<number> {
  const joinMode = opts.join ?? detectJoinMode(repoPath);
  if (joinMode) {
    console.error(
      "reposkein: found a committed .reposkein/meta.json — joining an existing repo " +
        "(skipping first-time scaffolding; wiring up your agent(s) automatically)."
    );
  }

  // 1) Indexer binary — but only attempt it on a platform that has one (or
  //    with an explicit offline override). Everything binary-dependent below
  //    degrades to a warning instead of crashing when neither is true.
  const platformSupported = platformKey() !== null || !!process.env.REPOSKEIN_INDEXER_BIN;
  let bin: string | null = null;
  if (!platformSupported) {
    console.error(cargoInstallFallbackMessage());
  } else {
    bin = await ensureIndexerBinary();
  }

  // 2) Git hooks (needs the indexer binary + a git repo). Also strips any
  //    merge declaration an older RepoSkein left behind for the derived
  //    JSONL, which is no longer committed.
  let hooksOk = false;
  if (bin) {
    try {
      const r = await spawnIndexer(bin, ["init", "--hooks", repoPath]);
      if (r.code !== 0) {
        console.error(`reposkein: indexer init failed: ${r.stderr || r.stdout}`);
        console.error("  (is this a git repository? run `git init` first.)");
        return 1;
      }
      hooksOk = true;
      // 2b) Keep the per-machine MCP config out of git; only .reposkein/ is shared.
      ensureLocalConfigGitignored(repoPath);
    } catch (err) {
      console.error(
        `reposkein: could not run the indexer binary (${err instanceof Error ? err.message : String(err)}).\n` +
          "  Set REPOSKEIN_INDEXER_BIN to a working `reposkein-indexer` path and re-run."
      );
    }
  } else {
    console.error(
      "reposkein: skipping git hook install and the initial index — no indexer binary for this platform."
    );
  }

  // 3) Build the initial code graph (the whole point of setup) unless opted out.
  if (bin && hooksOk && opts.index !== false) {
    console.error("reposkein: building the initial code graph…");
    const ic = await runIndex(repoPath);
    if (ic !== 0) {
      console.error(
        "reposkein: the initial index reported errors (see above) — re-run `reposkein-mcp index` later."
      );
    }
  }

  // 4) Install the navigation skill into the repo.
  const src = bundledSkillPath();
  if (existsSync(src)) {
    const dest = skillTargetPath(repoPath);
    mkdirSync(join(dest, ".."), { recursive: true });
    copyFileSync(src, dest);
    console.error(`reposkein: installed skill -> ${dest}`);
  } else {
    console.error("reposkein: bundled SKILL.md not found; skipping skill install.");
  }

  // 5) Optionally write the GitHub Pages publish workflow.
  if (opts.ci) writeCiWorkflow(repoPath);

  // 6) Join mode: auto-write agent MCP config + a doctor summary. First-time
  //    setup: print the config snippet for the user to paste in by hand.
  if (joinMode) {
    console.error("\nreposkein: wiring up local agent MCP config…");
    const results = writeAgentConfigs(repoPath, {
      agents: opts.agents,
      dryRun: opts.dryRun,
      ...opts.agentWriteOpts,
    });
    for (const r of results) console.error(formatAdapterResult(r));
    if (opts.dryRun) {
      console.error("\nreposkein: --dry-run — no config files were written. Re-run without --dry-run to apply.");
    }
    console.error("\nreposkein: doctor summary\n");
    console.error(renderDoctorReport(await runChecks(repoPath)));
  } else {
    console.error("\nreposkein: ready. Add this MCP server to your client config:\n");
    console.error(mcpConfigSnippet(repoPath));
    console.error(
      "\nCommit .reposkein/meta.json, config.toml, .gitignore, .gitattributes and summaries/. " +
        "nodes.jsonl and edges.jsonl are derived from your working tree and git-ignored: every clone " +
        "rebuilds them in seconds, and committing them would conflict on every branch that touches code. " +
        "Authored summaries live in .reposkein/summaries/<xx>.jsonl — one small file per hash bucket, so " +
        "two branches summarising different code never touch the same file." +
        "\nVerify anytime with `reposkein-mcp doctor`; re-index after big changes with `reposkein-mcp index` " +
        "(or the agent's reindex_file / init_cpg_skeleton tools)."
    );
  }
  return 0;
}
