import { mkdirSync, copyFileSync, existsSync, readFileSync, appendFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ensureIndexerBinary, packageRoot } from "../indexer/fetchBinary.js";
import { spawnIndexer } from "../indexer/runIndexer.js";

/** Where the navigation skill is installed for a repo (Claude project skills). */
export function skillTargetPath(repoPath: string): string {
  return join(repoPath, ".claude", "skills", "reposkein-graph-rag", "SKILL.md");
}

/** The bundled SKILL.md inside the installed package (dist/SKILL.md). */
export function bundledSkillPath(): string {
  return join(packageRoot(), "dist", "SKILL.md");
}

/** MCP server config snippet the user adds to their client (e.g. .mcp.json). */
export function mcpConfigSnippet(repoPath: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        reposkein: {
          command: "reposkein-mcp",
          env: { REPOSKEIN_REPO_PATH: repoPath },
        },
      },
    },
    null,
    2
  );
}

/** Per-machine MCP config files setup writes to a repo root: they hold absolute
 *  paths and a local backend password, so they must never be committed. */
const LOCAL_MCP_CONFIG_FILES = [".mcp.json", "opencode.json"] as const;

/** Idempotently add the per-machine MCP config files to the repo's .gitignore
 *  (creating it if absent), so `reposkein-mcp init` never leaves them tracked. */
export function ensureLocalConfigGitignored(repoPath: string): void {
  const gitignorePath = join(repoPath, ".gitignore");
  const current = existsSync(gitignorePath) ? readFileSync(gitignorePath, "utf8") : "";
  const present = new Set(current.split(/\r?\n/).map((line) => line.trim()));
  const missing = LOCAL_MCP_CONFIG_FILES.filter((file) => !present.has(file));
  if (missing.length === 0) return;
  const leadingNewline = current.length > 0 && !current.endsWith("\n") ? "\n" : "";
  const block =
    `${leadingNewline}\n# RepoSkein per-machine MCP config (absolute paths + a local backend\n` +
    "# password); regenerated per machine by `reposkein-mcp init`. The derived\n" +
    "# graph is ignored separately by .reposkein/.gitignore.\n" +
    `${missing.join("\n")}\n`;
  appendFileSync(gitignorePath, block);
  console.error(`reposkein: gitignored ${missing.join(", ")} (per-machine config, never commit)`);
}

/** Where `init --ci` writes the Pages-publish workflow in the target repo. */
export function ciWorkflowTargetPath(repoPath: string): string {
  return join(repoPath, ".github", "workflows", "reposkein-pages.yml");
}

/** Template written by `reposkein-mcp init --ci`: a thin caller of RepoSkein's
 *  reusable publish workflow (see docs/HOSTING.md). Consumers get released
 *  indexer binaries (no Rust toolchain) + a self-contained static export
 *  published to GitHub Pages. Repo owners must still flip Settings → Pages →
 *  "Build and deployment: GitHub Actions" once. */
export function ciWorkflowTemplate(): string {
  return `name: Publish RepoSkein constellation (GitHub Pages)

# Generated by \`reposkein-mcp init --ci\`. See docs/HOSTING.md — "Host your
# constellation" — before enabling: GitHub Pages is PUBLIC by default unless
# you're on GitHub Enterprise with private Pages enabled.
#
# ONE-TIME SETUP (repo owner): Settings → Pages → Build and deployment →
# Source: "GitHub Actions".

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    uses: reposkein/reposkein/.github/workflows/publish-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      repo-path: "."
`;
}

/** `reposkein-mcp init --ci`: writes the Pages-publish workflow template into
 *  the target repo's `.github/workflows/`. Non-destructive: skips (with a
 *  message) if the file already exists, so a re-run never clobbers a repo
 *  owner's edits. Returns whether it wrote the file. */
export function writeCiWorkflow(repoPath: string): { written: boolean; path: string } {
  const path = ciWorkflowTargetPath(repoPath);
  if (existsSync(path)) {
    console.error(`reposkein: ${path} already exists — leaving it untouched.`);
    return { written: false, path };
  }
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, ciWorkflowTemplate(), "utf8");
  console.error(`reposkein: wrote ${path} (see docs/HOSTING.md before enabling GitHub Pages).`);
  return { written: true, path };
}

/** `reposkein-mcp index [path]`: (re)build the code graph at `repoPath` using the
 *  native indexer. The package-friendly way to index — the `reposkein-indexer`
 *  binary is fetched into the package (not on PATH), so end users run this. */
export async function runIndex(repoPath = "."): Promise<number> {
  const bin = await ensureIndexerBinary();
  const r = await spawnIndexer(bin, ["index", repoPath]);
  if (r.stdout.trim()) console.error(r.stdout.trim());
  if (r.code !== 0) {
    console.error(`reposkein: index failed: ${r.stderr || r.stdout}`);
  }
  return r.code;
}

/** `reposkein-mcp init [path] [--no-index] [--ci]`: ensure the indexer, install git
 *  hooks, build the initial graph, install the navigation skill, print the MCP
 *  config + next steps. Pass `index: false` to skip the initial index; `ci: true`
 *  to also write the GitHub Pages publish workflow (see docs/HOSTING.md). */
export async function runInit(
  repoPath = ".",
  opts: { index?: boolean; ci?: boolean } = {}
): Promise<number> {
  // 1) Indexer binary (fetches it if needed).
  const bin = await ensureIndexerBinary();

  // 2) Git hooks (needs a git repo). Also strips any merge declaration an older
  //    RepoSkein left behind for the derived JSONL, which is no longer committed.
  const r = await spawnIndexer(bin, ["init", "--hooks", repoPath]);
  if (r.code !== 0) {
    console.error(`reposkein: indexer init failed: ${r.stderr || r.stdout}`);
    console.error("  (is this a git repository? run `git init` first.)");
    return 1;
  }

  // 2b) Keep the per-machine MCP config out of git; only .reposkein/ is shared.
  ensureLocalConfigGitignored(repoPath);

  // 3) Build the initial code graph (the whole point of setup) unless opted out.
  if (opts.index !== false) {
    console.error("reposkein: building the initial code graph…");
    const ic = await runIndex(repoPath);
    if (ic !== 0) {
      console.error(
        "reposkein: the initial index reported errors (see above) — re-run `reposkein-mcp index` later."
      );
    }
  }

  // 4) Install the navigation skill into the repo.
  const src = bundledSkillPath();
  if (existsSync(src)) {
    const dest = skillTargetPath(repoPath);
    mkdirSync(join(dest, ".."), { recursive: true });
    copyFileSync(src, dest);
    console.error(`reposkein: installed skill -> ${dest}`);
  } else {
    console.error("reposkein: bundled SKILL.md not found; skipping skill install.");
  }

  // 5) Optionally write the GitHub Pages publish workflow.
  if (opts.ci) writeCiWorkflow(repoPath);

  // 6) Next steps + MCP config.
  console.error("\nreposkein: ready. Add this MCP server to your client config:\n");
  console.error(mcpConfigSnippet(repoPath));
  console.error(
    "\nCommit .reposkein/meta.json, config.toml, .gitignore, .gitattributes and summaries/. " +
      "nodes.jsonl and edges.jsonl are derived from your working tree and git-ignored: every clone " +
      "rebuilds them in seconds, and committing them would conflict on every branch that touches code. " +
      "Authored summaries live in .reposkein/summaries/<xx>.jsonl — one small file per hash bucket, so " +
      "two branches summarising different code never touch the same file." +
      "\nVerify anytime with `reposkein-mcp doctor`; re-index after big changes with `reposkein-mcp index` " +
      "(or the agent's reindex_file / init_cpg_skeleton tools)."
  );
  return 0;
}
