/** Command-palette node-row iconography: a single-character glyph per node
 *  kind, plus the CSS custom-property name that holds its color (generated by
 *  `styles/tokens.ts` from `scene/encoding.ts` — see `NODE_KIND_META`).
 *
 *  The glyph is a SEPARATE signal from the color dot (design: "kind glyph +
 *  colored dot") — deliberately so kind is legible without relying on color
 *  alone (a colorblind-friendly redundancy the scene's node coloring doesn't
 *  otherwise have).
 *
 *  Both functions take a `NodeRecord.kind` — the RAW graph label
 *  (`"Function"`, `"File"`, `"Directory"`, `"Repository"`, ...). `NODE_KIND_META`
 *  (and the tokens generated from it) key structural rows by the SHORTER
 *  `ClusterKind` vocabulary instead (`"galaxy"|"dir"|"file"`), so the three
 *  structural labels are normalized to that vocabulary before lookup; symbol
 *  labels (`"Function"` etc.) already match `NODE_KIND_META` verbatim and
 *  pass through unchanged.
 *
 *  `nodeKindColorVar` reproduces `styles/tokens.ts`'s `tokenSlug` locally
 *  rather than importing it: `styles/` is a leaf (Vite-plugin-only) module,
 *  and duplicating a three-line slug function is cheaper than inverting that
 *  dependency direction. Keep the two slug functions in sync if either changes
 *  (`tokens.test.ts` would catch a drift in the generated CSS var names). */

/** Raw structural label → the ClusterKind key NODE_KIND_META actually uses. */
const STRUCTURAL_KIND: Record<string, string> = {
  Repository: "galaxy",
  Directory: "dir",
  File: "file",
};

function normalizeKind(kind: string): string {
  return STRUCTURAL_KIND[kind] ?? kind; // symbol kinds pass through unchanged.
}

const GLYPH: Record<string, string> = {
  galaxy: "◎",
  dir: "▤",
  file: "▯",
  Function: "ƒ",
  Class: "◆",
  Interface: "◇",
  Enum: "≡",
  Variable: "•",
};

const DEFAULT_GLYPH = "○";

export function nodeKindGlyph(kind: string): string {
  return GLYPH[normalizeKind(kind)] ?? DEFAULT_GLYPH;
}

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** e.g. `nodeKindColorVar("Function")` → `"var(--color-node-function)"`;
 *  `nodeKindColorVar("File")` → `"var(--color-node-file)"`. */
export function nodeKindColorVar(kind: string): string {
  return `var(--color-node-${slug(normalizeKind(kind))})`;
}
