/** Command-palette node-row iconography: a single-character glyph per node
 *  kind, plus the CSS custom-property name that holds its color (generated by
 *  `styles/tokens.ts` from `scene/encoding.ts` — see `NODE_KIND_META`).
 *
 *  The glyph is a SEPARATE signal from the color dot (design: "kind glyph +
 *  colored dot") — deliberately so kind is legible without relying on color
 *  alone (a colorblind-friendly redundancy the scene's node coloring doesn't
 *  otherwise have).
 *
 *  Both functions take a `NodeRecord.kind` — the RAW graph label
 *  (`"Function"`, `"File"`, `"Directory"`, `"Repository"`, ...). `NODE_KIND_META`
 *  (and the tokens generated from it) key structural rows by the SHORTER
 *  `ClusterKind` vocabulary instead (`"galaxy"|"dir"|"file"`), so the three
 *  structural labels are normalized to that vocabulary before lookup; symbol
 *  labels (`"Function"` etc.) already match `NODE_KIND_META` verbatim and
 *  pass through unchanged.
 *
 *  The kind→CSS-var mapping itself lives in `data/encodingVars.ts` (shared with
 *  the legend sheet and the filter chips so all three name the SAME token —
 *  see `panels/colorIdentity.test.tsx`); `nodeKindColorVar` is re-exported here
 *  so existing call sites keep their import. */

import { nodeKindColorVar, normalizeNodeKind } from "./encodingVars";

export { nodeKindColorVar };

const normalizeKind = normalizeNodeKind;

const GLYPH: Record<string, string> = {
  galaxy: "◎",
  dir: "▤",
  file: "▯",
  Function: "ƒ",
  Class: "◆",
  Interface: "◇",
  Enum: "≡",
  Variable: "•",
};

const DEFAULT_GLYPH = "○";

export function nodeKindGlyph(kind: string): string {
  return GLYPH[normalizeKind(kind)] ?? DEFAULT_GLYPH;
}

